name: wimi_app
description: "Una aplicación móvil gamificada para aprender finanzas personales de forma divertida, inspirada en Duolingo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Navegación
  cupertino_icons: ^1.0.6
  go_router: ^14.6.2

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.3
  firebase_analytics: ^11.3.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3

  # Utilidades
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  http: ^1.2.2

  # Multimedia
  audioplayers: ^6.1.0

  # Geolocalización
  geolocator: ^13.0.1

  # Información del dispositivo
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/