name: wimi_app
description: "Una aplicación móvil gamificada para aprender finanzas personales de forma divertida, inspirada en Duolingo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Navegación
  cupertino_icons: ^1.0.6
  go_router: ^14.6.2

  # State Management
  provider: ^6.1.2

  # Firebase (Backend completo)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.3
  firebase_analytics: ^11.3.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+7

  # Networking y APIs
  http: ^1.2.2
  dio: ^5.7.0  # HTTP client más avanzado
  connectivity_plus: ^6.0.5

  # Cache y Persistencia Local
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1

  # Multimedia y Assets
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2  # Animaciones avanzadas

  # Utilidades de Dispositivo
  geolocator: ^13.0.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.1

  # Notificaciones
  flutter_local_notifications: ^17.2.3
  awesome_notifications: ^0.9.3+1

  # Internacionalización
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Seguridad
  crypto: ^3.0.5
  encrypt: ^5.0.3

  # Generación de Contenido IA
  # openai_dart: ^0.3.0  # Para ChatGPT (descomentar cuando sea necesario)
  
  # Generación de PDFs y Reportes
  pdf: ^3.11.1
  printing: ^5.13.2

  # Análisis y Métricas
  sentry_flutter: ^8.9.0  # Monitoreo de errores
  
  # Utilidades de Desarrollo
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Generación de código
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # Testing avanzado
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/videos/
    - assets/fonts/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300