name: wimi_app
description: "Una aplicación móvil gamificada para aprender finanzas personales de forma divertida, inspirada en Duolingo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI y Navegación
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2

  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # Firebase (Versiones compatibles actuales)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.3
  firebase_analytics: ^11.3.3
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.1.3
  firebase_crashlytics: ^4.1.3

  # Utilidades
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  http: ^1.2.2
  dio: ^5.8.0

  # Multimedia
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1

  # Conectividad
  connectivity_plus: ^6.1.0

  # Geolocalización
  geolocator: ^13.0.1

  # Información del dispositivo
  device_info_plus: ^11.5.0

  # Testing y Debugging
  flutter_dotenv: ^5.2.1
  logger: ^2.4.0

  # Performance y Analytics
  sentry_flutter: ^8.11.0

  # UI/UX Enhancements
  flutter_animate: ^4.5.0
  lottie: ^3.3.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

  # Internacionalización
  intl: ^0.20.1
  flutter_localizations:
    sdk: flutter

  # Utilities
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    - assets/lottie/
    - .env