// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLXBXwfF_oyNYs37xB_f5xbs7i4UKiGS0',
    appId: '1:427127271682:web:7253383b486dff69d9121b',
    messagingSenderId: '427127271682',
    projectId: 'wimi-app-1c105',
    authDomain: 'wimi-app-1c105.firebaseapp.com',
    storageBucket: 'wimi-app-1c105.firebasestorage.app',
    measurementId: 'G-HYFW1FGSMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDzVgjAqgRf24KJ6Pa00JLuwD81sp8ro',
    appId: '1:427127271682:android:ad3bffa2a29d65a9d9121b',
    messagingSenderId: '427127271682',
    projectId: 'wimi-app-1c105',
    storageBucket: 'wimi-app-1c105.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfo9uTOK59gT_dn_LO99SiNQmyB2AU7FM',
    appId: '1:427127271682:ios:c74fb6b761a2708cd9121b',
    messagingSenderId: '427127271682',
    projectId: 'wimi-app-1c105',
    storageBucket: 'wimi-app-1c105.firebasestorage.app',
    iosBundleId: 'com.example.wimiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfo9uTOK59gT_dn_LO99SiNQmyB2AU7FM',
    appId: '1:427127271682:ios:c74fb6b761a2708cd9121b',
    messagingSenderId: '427127271682',
    projectId: 'wimi-app-1c105',
    storageBucket: 'wimi-app-1c105.firebasestorage.app',
    iosBundleId: 'com.example.wimiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLXBXwfF_oyNYs37xB_f5xbs7i4UKiGS0',
    appId: '1:427127271682:web:7253383b486dff69d9121b',
    messagingSenderId: '427127271682',
    projectId: 'wimi-app-1c105',
    authDomain: 'wimi-app-1c105.firebaseapp.com',
    storageBucket: 'wimi-app-1c105.firebasestorage.app',
    measurementId: 'G-HYFW1FGSMN',
  );
}
